### ISSUE TITLE
EIP140: REVERT

### ISSUE THREAD

**Issue by pirapira** [ethereum/yellowpaper#232]
This issue keeps track of adoption of https://github.com/ethereum/EIPs/pull/206 <del>and https://github.com/ethereum/EIPs/pull/207/files</del>, which introduce the REVERT instruction.

EDIT: https://github.com/ethereum/EIPs/pull/207 is not about protocol consensus anyway, so not relevant for the Yellow Paper.

**Comment by pirapira** [comment]
* [ ] The sentence "no instruction can, through its instruction, cause an exceptional halt" needs to be changed.

**Comment by pirapira** [comment]
* [ ] `\Xi` and `\Lambda` needs to return gas after REVERT.

**Comment by pirapira** [comment]
#238 and #239 needs to be fixed first.  Otherwise, the gas-returning nature of REVERT cannot be expressed.

**Comment by msuiche** [comment]
@pirapira Can we expect the *REVERT* instruction to be appended to the yellowpaper ?

If not it would be misleading to not have every instruction documented by the yellowpaper, especially when they can be found in the instruction list of the source code of Solidity:
https://github.com/ethereum/solidity/blob/develop/libevmasm/Instruction.cpp#L162

Or is it because it hasn't been merge to `release` branch yet ?

**Comment by pirapira** [comment]
@msuiche there is a pull-request https://github.com/ethereum/yellowpaper/pull/242 about that.
