### ISSUE TITLE
Use roman fonts for subscripts _b (balance) _c (code) and so on

### ISSUE THREAD

**Issue by pirapira** [ethereum/yellowpaper#289]
Currently, an account's balance is typeset `a_b` with the italic `b`, however, since this `b` is not a variable but a name of a field, the `b` should be typeset in a roman font.  The same can be said for `_c` for code, `_n` for nonce and `_s`, as well as elements of substates, blocks and transactions.

**Comment by jamesray1** [comment]
I will make the changes in https://github.com/jamesray1/yellowpaper.

**Comment by jamesray1** [comment]
e39fbc88a1ee2458ba7a56f852bba79b4196c25a

**Comment by jamesray1** [comment]
Actually I used `\mathbf` instead of `rm`. I hope that's not a big deal, otherwise it will need to be changed again!

**Comment by fulldecent** [comment]
@jamesray1 The link to e39fbc8 works, but (for some reason) I can't see which branches it is included in. Is there a PR for this commit?

**Comment by jamesray1** [comment]
This was ages ago in an outdated PR (which was in a branch that has been deleted) that has since been replaced with #401, which is in the process of being split up. These particular changes have been merged with 35aa14dbee39853f4d5295b8f9a2fed0f5b7dadf, while commits immediately after that removed mathrms that were wrongly added. I'm pretty sure that this issue can safely be closed now.

**Comment by pirapira** [comment]
Yes, \mathrm has been added in so many places that a mistake would stand out.
