### ISSUE TITLE
Specify all past hard forks in the Yellow Paper

### ISSUE THREAD

**Issue by jamesray1** [ethereum/yellowpaper#653]
We could create a branch for the DAO hard fork as well as all other versions that have not been specified yet (I believe this is already on the to-do list), defining the differences in sections. However, we do have the branches.md file which links to the changes in all past hard forks.

**Comment by nicksavers** [comment]
If you specify the DAO hard fork in a PR we can have a look. Not sure what the point is of having a branch just for the fork. Closing this.

I suppose the merge would need be done on `homestead` and all other branches after that. Since it was such a rare event, I'm not even sure you can put this in the consensus rules somewhere. Perhaps in Appendix K.

**Comment by jamesray1** [comment]
OK, I'll do this at the end of the month at the soonest, as I need to really focus on working on Drops of Diamond / Parity stateless sharding.

**Comment by jamesray1** [comment]
Or I may just not do it at all.
