### ISSUE TITLE
Maintainer(s) for this repo

### ISSUE THREAD

**Issue by bmann** [ethereum/yellowpaper#725]
Hey all, trying to figure out who maintains this repo, and is reviewing PRs and other items on a regular basis. 

From last three commits @acoglio, @tjade273, @nicksavers — do any of you consider yourself maintainers?

Do you need help? Would you be open to adding more maintainers?

**Comment by acoglio** [comment]
Hi @bmann, I believe that a group to maintain the YP will be formed soon. Somebody from the Ethereum Foundation is organizing this. I'll let him know that you are interested in contributing.

**Comment by bmann** [comment]
Thanks for responding @acoglio — please have the somebody come let us know in the EthMagicians forum https://ethereum-magicians.org/t/yellow-paper-maintainership/819

**Comment by acoglio** [comment]
I see now that James Pitts (to whom I was referring) has started a thread on the Ethereum Magicians web site. I think these this and that thread are "in sync" now.

**Comment by nicksavers** [comment]
@bmann I've been merging fixes and Constantinople changes into the repository ever since @gavofyork added a license to it and will keep doing that time-permitting. Of course useful additions and corrections are always welcome. If you have any questions to me personally, feel free to ask me on Gitter.

**Comment by bmann** [comment]
@nicksavers thanks for responding. Sounds like you’re a maintainer ;) I’ll update the wiki page.
