### ISSUE TITLE
Disambiguate "c" function for PUSH2-32 instructions when used on ranges

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/yellowpaper#83]
https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L1816

When a push operation requires more bytes than exists in the code, the "c" function ensures bytes default to zero. The function is defined as applied to an index, but then it's used on an index range in definitions of PUSH2-32 instructions.

If the meaning is to map c over the range, then the program
0x7f010203 would be equal to 0x7f0102030000000000000000000000000000000000000000000000000000000000

The Go client does not implement the above behavior; rather it considers
0x7f010203 equal to
0x7f0000000000000000000000000000000000000000000000000000000000010203

The behavior of the "c' function on index ranges should be formalized.

**Comment by CJentzsch** [comment]
On the other hand, when PUSH is the last command of the evm code, the result can be discarded. Therefore, when reaching the end of the evm code ( the else branch in the PUSH{x} definition in the YP) one does not need to execute PUSH anymore and can just leave the stack as it is, because the stack will be cleared anyway.
